#!/usr/bin/env python3
"""Apply the reviewed semantic and observable-grounding tail to a generated batch.

The deterministic generation gate catches schema, leakage, length, and basic
termination contradictions.  It cannot prove that every compound scenario goal was
handled.  This script records the outcome of a complete decision-disagreement review
plus a second full-batch pass over typed identifiers, DOBs, conditional arithmetic,
compound preferences, and hard historical-prefix contamination.

Every source state was generated by DeepSeek.  The small reviewed tail is intentionally
kept explicit: it is safer and more reproducible than weakening a global heuristic or
silently presenting corrected targets as untouched teacher output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(PROJECT_ROOT))

from src.user_simulator_data.contracts import (  # noqa: E402
    STOP_TOKEN,
    TeacherDecision,
    build_sft_record,
    validate_response_constraints,
    validate_teacher_decision,
)
from src.user_simulator_data.generation import summarize_generations  # noqa: E402


AUDIT_VERSION = "tau-airline-usim-full-semantic-grounding-audit-v2"
SOURCE_PROMPT_VERSION = "tau-airline-usim-teacher-v1.5"

# The raw v1.5 batch is immutable evidence.  Case-builder v2 retains each repairable
# contamination root and removes only later states in the same trajectory.  Recording
# roots is less brittle than hand-listing every excluded downstream turn; the exact
# excluded set is derived and verified below from these roots and the raw case IDs.
EXPECTED_CONTEXT_CUT_ROOTS = {
    "historical-airline-t0001-trial01-u019",
    "historical-airline-t0001-trial02-u003",
    "historical-airline-t0001-trial03-u003",
    "historical-airline-t0001-trial04-u003",
    "historical-airline-t0001-trial05-u003",
    "historical-airline-t0019-trial00-u011",
    "historical-airline-t0021-trial05-u003",
    "historical-airline-t0021-trial06-u003",
    "historical-airline-t0022-trial01-u003",
    "historical-airline-t0022-trial04-u003",
    "historical-airline-t0025-trial00-u017",
    "historical-airline-t0032-trial04-u009",
    "historical-airline-t0040-trial01-u017",
    "historical-airline-t0040-trial06-u017",
    "historical-airline-t0040-trial07-u017",
}

# These four STOP decisions omitted an explicit scenario goal that remained observable
# in the conversation.  The corrected responses use no hidden tool state or gold output.
PREMATURE_STOP_OVERRIDES: dict[str, dict[str, Any]] = {
    "historical-airline-t0004-trial00-u025": {
        "response": "I also still need the passenger name changed to my name. Can you help with that?",
        "unresolved_goals": ["change the passenger name to Omar Rossi"],
        "reason": "passenger-name goal was omitted",
    },
    "historical-airline-t0007-trial01-u029": {
        "response": (
            "That doesn't match my booking—I expected an economy ticket, not business. "
            "Could you check again using my user ID?"
        ),
        "unresolved_goals": ["locate the correct reservation before changing the flight"],
        "reason": "agent-visible reservation details contradicted the customer",
    },
    "historical-airline-t0004-trial04-u023": {
        "response": "Yes, I'd like to use my gift card for the payment.",
        "unresolved_goals": ["apply the requested gift-card payment"],
        "reason": "preferred payment method remained unresolved",
    },
    "historical-airline-t0034-trial05-u033": {
        "response": "I still want to cancel reservation XEHM4B regardless of the policy.",
        "unresolved_goals": ["attempt cancellation of the remaining requested reservation"],
        "reason": "another explicitly requested reservation remained uncancelled",
    },
}

# The review found these continuations to be delayed termination: the response merely
# thanked/reconfirmed, repeated an action already completed, required unavailable
# information, or invented a fallback absent from the scenario.  The value records the
# honest terminal semantics for audit metadata; the Student target is always STOP.
FORCED_STOP_OVERRIDES: dict[str, dict[str, str]] = {
    "historical-airline-t0000-trial00-u041": {"termination_reason": "goal_satisfied", "reason": "booking and stated preferences were communicated"},
    "historical-airline-t0009-trial00-u033": {"termination_reason": "goal_satisfied", "reason": "Mastercard charge was already stated explicitly"},
    "historical-airline-t0013-trial00-u047": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0044-trial00-u015": {"termination_reason": "goal_satisfied", "reason": "numeric maximum baggage answer was already provided"},
    "historical-airline-t0007-trial01-u047": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0008-trial01-u053": {"termination_reason": "goal_satisfied", "reason": "new booking and visible Mastercard charge were communicated"},
    "historical-airline-t0011-trial01-u029": {"termination_reason": "goal_satisfied", "reason": "certificate balance and fallback payment flow were already completed"},
    "historical-airline-t0014-trial01-u021": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0031-trial01-u025": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted"},
    "historical-airline-t0035-trial01-u019": {"termination_reason": "goal_failed", "reason": "all scenario-provided fallbacks were exhausted"},
    "historical-airline-t0044-trial01-u013": {"termination_reason": "goal_satisfied", "reason": "numeric baggage allowance was already communicated"},
    "historical-airline-t0045-trial01-u017": {"termination_reason": "goal_satisfied", "reason": "passenger-count correction behavior was completed"},
    "historical-airline-t0004-trial02-u027": {"termination_reason": "goal_satisfied", "reason": "accepted feasible changes and payment preference were completed"},
    "historical-airline-t0013-trial02-u037": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0014-trial02-u023": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0015-trial02-u027": {"termination_reason": "goal_satisfied", "reason": "refund destination was already stated explicitly"},
    "historical-airline-t0017-trial02-u039": {"termination_reason": "goal_satisfied", "reason": "selected flight change and payment were already processed"},
    "historical-airline-t0019-trial02-u017": {"termination_reason": "goal_satisfied", "reason": "requested changes and refund amount were already stated"},
    "historical-airline-t0037-trial02-u025": {"termination_reason": "goal_satisfied", "reason": "scenario compensation fallback was completed; certificate terms were not a goal"},
    "historical-airline-t0044-trial02-u013": {"termination_reason": "goal_satisfied", "reason": "numeric baggage allowance was already confirmed"},
    "historical-airline-t0009-trial03-u039": {"termination_reason": "goal_satisfied", "reason": "total Mastercard charge was already stated explicitly"},
    "historical-airline-t0025-trial03-u035": {"termination_reason": "goal_satisfied", "reason": "cancellation attempt and replacement booking sequence was complete"},
    "historical-airline-t0031-trial03-u017": {"termination_reason": "cannot_continue", "reason": "requested cancellation required a reason absent from the scenario"},
    "historical-airline-t0032-trial03-u021": {"termination_reason": "goal_satisfied", "reason": "booking constraints and final price were communicated"},
    "historical-airline-t0037-trial03-u027": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was complete; extra certificate terms were not a goal"},
    "historical-airline-t0047-trial03-u007": {"termination_reason": "cannot_continue", "reason": "cancellation could not proceed without the missing reservation ID"},
    "historical-airline-t0009-trial04-u059": {"termination_reason": "goal_satisfied", "reason": "total Mastercard charge was already stated explicitly"},
    "historical-airline-t0013-trial04-u015": {"termination_reason": "goal_failed", "reason": "requested destination change was disallowed and no instructed fallback remained"},
    "historical-airline-t0014-trial04-u019": {"termination_reason": "goal_failed", "reason": "companion-only upgrade was disallowed; a new split-booking goal was not instructed"},
    "historical-airline-t0031-trial04-u023": {"termination_reason": "cannot_continue", "reason": "requested cancellation required a reason absent from the scenario"},
    "historical-airline-t0037-trial04-u027": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was issued"},
    "historical-airline-t0014-trial05-u027": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0031-trial05-u025": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted; transfer was not requested"},
    "historical-airline-t0037-trial05-u023": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was issued; certificate terms were not a goal"},
    "historical-airline-t0001-trial06-u019": {"termination_reason": "goal_satisfied", "reason": "insurance cancellation fallback completed and rebooking could occur later"},
    "historical-airline-t0007-trial06-u037": {"termination_reason": "cannot_continue", "reason": "customer explicitly left to retrieve correct booking information"},
    "historical-airline-t0014-trial06-u021": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0017-trial06-u033": {"termination_reason": "goal_satisfied", "reason": "selected outbound date and cabin changes were processed"},
    "historical-airline-t0031-trial06-u031": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted; transfer was not requested"},
    "historical-airline-t0013-trial07-u035": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
}

# These decisions should continue, but the original target either contradicted itself or
# failed to ask for the actual unresolved value.
CONTINUE_REWRITES: dict[str, dict[str, Any]] = {
    "historical-airline-t0024-trial05-u017": {
        "response": "No—the $222 total is above my $200 budget, so please do not make any changes.",
        "unresolved_goals": ["confirm that no changes will be made"],
        "reason": "remove contradictory proceed/cancel wording while communicating the budget decision",
    },
    "historical-airline-t0044-trial07-u013": {
        "response": (
            "I understand that 4 bags are free, but what is the maximum total number "
            "I can bring if I pay for extra bags? Please give me one number."
        ),
        "unresolved_goals": ["obtain the maximum total baggage count including paid bags"],
        "reason": "ask for the requested total maximum instead of restating the free allowance",
    },
}

# The first audit reviewed all 70 decision disagreements.  This second pass inspects
# same-decision semantic failures that a STOP/CONTINUE comparison cannot reveal.
FULL_SEMANTIC_REWRITES: dict[str, dict[str, str]] = {
    **{
        f"historical-airline-t0002-trial{trial:02d}-u003": {
            "response": (
                "My user ID is omar_davis_3817. I don't have the reservation IDs, "
                "so please check all bookings in my profile. I need every business "
                "flight changed to economy and the total savings."
            ),
            "reason": "remove invented IDs and textual stage directions while preserving all goals",
        }
        for trial in (0, 5, 6, 7)
    },
    "historical-airline-t0006-trial00-u003": {
        "response": (
            "My user ID is aarav_garcia_1177, but I don't have the reservation ID. "
            "Can you use my account to find my upcoming ATL-to-PHL booking?"
        ),
        "reason": "avoid describing the user ID as a personal name",
    },
    "historical-airline-t0007-trial05-u003": {
        "response": (
            "My user ID is aarav_garcia_1177, but I don't have the reservation ID. "
            "Can you use my account to find my upcoming ATL-to-PHL booking?"
        ),
        "reason": "avoid inferring a full name from the user ID",
    },
    **{
        f"historical-airline-t0001-trial{trial:02d}-u003": {
            "response": (
                "My user ID is olivia_gonzalez_2305. I don't remember the reservation "
                "ID; it's the half-day round trip to Texas with a 3 PM return to "
                "Newark. Can you locate it from my account?"
            ),
            "reason": "remove unsupported Dallas/Fort Worth specificity",
        }
        for trial in range(6)
    },
    "historical-airline-t0001-trial01-u019": {
        "response": (
            "I still can't find the reservation ID or a reliable flight number. "
            "Can you use my user ID and the Newark-to-Texas trip details to locate it?"
        ),
        "reason": "both Teacher and historical reference invented booking identifiers",
    },
    "historical-airline-t0019-trial00-u011": {
        "response": (
            "I'll take HAT169 outbound and HAT088 return, and add one checked bag. "
            "I don't have a payment ID, so please use a valid method from my profile."
        ),
        "reason": "remove unsupported payment identifier while preserving chosen flights",
    },
    "historical-airline-t0032-trial04-u009": {
        "response": (
            "I'd like HAT271. Kevin's DOB is April 12, 2001; I don't remember my own "
            "DOB, so please use my profile. No bags or insurance, and use the card "
            "ending in 7238."
        ),
        "reason": "both Teacher and historical reference invented the customer's DOB",
    },
    "historical-airline-t0011-trial01-u019": {
        "response": (
            "Since $125 would remain on the certificate, that's more than $100. "
            "Please use my gift card and credit card instead."
        ),
        "reason": "fix inverted certificate-waste condition",
    },
    "historical-airline-t0011-trial06-u013": {
        "response": (
            "If $201 would remain on the certificate, that's more than $100. "
            "Please use my gift card and credit card instead."
        ),
        "reason": "fix less-than/more-than inversion in payment fallback",
    },
    **{
        case_id: {
            "response": response,
            "reason": "replace an invented reservation with a grounded, progressive cancellation request",
        }
        for case_id, response in {
            "historical-airline-t0012-trial05-u003": (
                "My user ID is amelia_sanchez_4739. I don't have the reservation ID, "
                "but I need to cancel my MCO-to-CLT flight because my plans changed "
                "and receive the applicable refund. Can you locate it from my account?"
            ),
            "historical-airline-t0012-trial05-u007": (
                "I still can't find the reservation ID. My user ID is "
                "amelia_sanchez_4739; can you use it to locate and cancel my "
                "MCO-to-CLT flight?"
            ),
            "historical-airline-t0012-trial05-u011": (
                "I still can't find the reservation ID. My user ID is "
                "amelia_sanchez_4739; please use my account to find and cancel the "
                "MCO-to-CLT flight."
            ),
            "historical-airline-t0012-trial07-u003": (
                "My user ID is amelia_sanchez_4739. I don't have the reservation ID. "
                "I need to cancel my MCO-to-CLT flight because my plans changed and "
                "receive the applicable refund."
            ),
        }.items()
    },
    **{
        f"historical-airline-t0021-trial{trial:02d}-u003": {
            "response": (
                "My user ID is daiki_lee_6144, but I don't have the reservation ID. "
                "Can you use my account to find my May 17 flight from JFK and help "
                "change it to a nonstop flight?"
            ),
            "reason": "remove invented reservation, route, and cabin details",
        }
        for trial in range(8)
    },
    **{
        f"historical-airline-t0022-trial{trial:02d}-u003": {
            "response": (
                "My user ID is ivan_rossi_8555. I don't have the reservation ID or "
                "destination details handy. Can you use my account to find my May 21 "
                "flight from EWR and help change it to a nonstop flight?"
            ),
            "reason": "remove user-ID type confusion and unsupported destination details",
        }
        for trial in range(8)
    },
    "historical-airline-t0025-trial00-u017": {
        "response": (
            "I'll take the second-cheapest economy option: HAT069 plus HAT011 "
            "for $300. Please help me book that itinerary."
        ),
        "reason": "select the actual second-cheapest option instead of the cheapest direct flight",
    },
    "historical-airline-t0025-trial04-u003": {
        "response": (
            "My user ID is aarav_ahmed_6699, but I don't have the reservation ID. "
            "Please use my account to find the May 22 JFK-to-MCO booking I need to cancel."
        ),
        "reason": "avoid inferring a full name and preserve the typed user identifier",
    },
    "historical-airline-t0025-trial03-u011": {
        "response": (
            "Please show me the other economy options first. I want the "
            "second-cheapest flight, not automatically the only one shown."
        ),
        "reason": "preserve second-cheapest preference before booking",
    },
    "historical-airline-t0025-trial03-u017": {
        "response": (
            "Actually, I need the second-cheapest economy option: HAT069 plus "
            "HAT258 for $290, not HAT023. Please use that itinerary."
        ),
        "reason": "repair historical cheapest-flight drift and remove invented DOB",
    },
    "historical-airline-t0025-trial04-u019": {
        "response": (
            "Please give me the economy prices for the one-stop options so I can "
            "identify the second-cheapest option overall."
        ),
        "reason": "the listed one-stop options had no prices, so second-cheapest was unknown",
    },
    "historical-airline-t0025-trial05-u015": {
        "response": (
            "Could you show me the other economy options first? I want the "
            "second-cheapest flight before I provide booking details."
        ),
        "reason": "avoid accepting the first/cheapest flight and inventing a DOB",
    },
    "historical-airline-t0025-trial05-u025": {
        "response": (
            "I need the second-cheapest option, HAT069 plus HAT258 for $290, "
            "not HAT023. Please switch back to that itinerary."
        ),
        "reason": "restore the explicit second-cheapest preference after historical drift",
    },
    **{
        f"historical-airline-t0031-trial{trial:02d}-u003": {
            "response": (
                "My user ID is mohamed_hernandez_5188, but I don't have the "
                "reservation ID. Can you use my account to find the duplicate May 17 "
                "booking from ATL to JFK?"
            ),
            "reason": "state the user ID with the correct type and remove stage-like hesitation",
        }
        for trial in (6, 7)
    },
    **{
        f"historical-airline-t0040-trial{trial:02d}-u017": {
            "response": (
                "I don't have the exact route or date with me. I only know the airline "
                "canceled it earlier this month and I missed an important meeting. "
                "Can you use my account history and help with compensation?"
            ),
            "reason": "remove unsupported route/date details from the compensation claim",
        }
        for trial in (1, 4, 6, 7)
    },
    **{
        f"historical-airline-t0047-trial{trial:02d}-u003": {
            "response": (
                "I don't have the reservation ID. I'm Raj Sanchez, user ID "
                "raj_sanchez_7340. The phone representative told me to cancel through "
                "this service agent; can you locate the booking from my account?"
            ),
            "reason": "remove invented/example reservation IDs and preserve the phone-support condition",
        }
        for trial in range(8)
        if trial != 5
    },
}


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            value = json.loads(line)
            if not isinstance(value, dict):
                raise RuntimeError(f"expected object at {path}:{line_number}")
            rows.append(value)
    return rows


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _quality_issues(decision: TeacherDecision, case: dict[str, Any]) -> list[str]:
    privileged = case.get("privileged_reference", {})
    issues = validate_teacher_decision(
        decision,
        scenario=str(case.get("scenario", "")),
        observable_history=case.get("observable_history", []),
        privileged_entities=privileged.get("privileged_entities", []),
    )
    issues.extend(validate_response_constraints(decision, case.get("response_constraints")))
    return sorted(set(issues))


_GROUNDING_ISSUE_PREFIXES = (
    "agent_example_copied_",
    "placeholder_identifier:",
    "template_placeholder_",
    "unsupported_",
    "user_id_mislabeled_",
)


def _grounding_issues(decision: TeacherDecision, case: dict[str, Any]) -> list[str]:
    return [
        issue
        for issue in _quality_issues(decision, case)
        if issue.startswith(_GROUNDING_ISSUE_PREFIXES)
    ]


def _stop_decision(original: TeacherDecision, termination_reason: str) -> TeacherDecision:
    if termination_reason == "goal_satisfied":
        goal_status = "satisfied"
    elif termination_reason == "goal_failed":
        goal_status = "failed"
    elif termination_reason == "cannot_continue":
        goal_status = "blocked"
    else:
        raise RuntimeError(f"unsupported audited termination reason: {termination_reason}")
    return replace(
        original,
        decision="stop",
        is_over=True,
        termination_reason=termination_reason,
        goal_status=goal_status,
        communication_status="complete",
        response=STOP_TOKEN,
        resolved_goals=(
            original.resolved_goals
            if original.resolved_goals
            else ("reviewed observable interaction boundary",)
        ),
        unresolved_goals=(),
        evidence=(),
    )


def _task_trial_turn(case_id: str) -> tuple[int, int, int]:
    match = re.fullmatch(r"historical-airline-t(\d+)-trial(\d+)-u(\d+)", case_id)
    if not match:
        raise RuntimeError(f"unexpected historical case ID: {case_id}")
    return tuple(int(value) for value in match.groups())


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--cases", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.input.resolve() == args.output.resolve():
        raise RuntimeError("audited output must not overwrite the raw generation")
    rows = _read_jsonl(args.input)
    cases = _read_jsonl(args.cases)
    case_by_id = {str(case["case_id"]): case for case in cases}
    row_ids = [str(row.get("case_id", "")) for row in rows]
    if len(set(row_ids)) != len(row_ids) or len(case_by_id) != len(cases):
        raise RuntimeError("duplicate case_id detected")
    raw_ids = set(row_ids)
    case_ids = set(case_by_id)
    missing_raw = case_ids - raw_ids
    context_excluded_ids = raw_ids - case_ids
    if missing_raw:
        raise RuntimeError(f"generation is missing source cases: {sorted(missing_raw)}")
    context_cut_roots = {
        case_id
        for case_id, case in case_by_id.items()
        if case.get("reference_grounding_issues")
    }
    if context_cut_roots != EXPECTED_CONTEXT_CUT_ROOTS:
        raise RuntimeError(
            "historical context-cut roots changed; repeat semantic review: "
            f"{sorted(context_cut_roots)}"
        )
    root_turn_by_trajectory = {
        (task_id, trial): turn
        for task_id, trial, turn in map(_task_trial_turn, context_cut_roots)
    }
    expected_context_excluded_ids = {
        case_id
        for case_id in raw_ids
        for task_id, trial, turn in [_task_trial_turn(case_id)]
        if turn > root_turn_by_trajectory.get((task_id, trial), turn)
    }
    if context_excluded_ids != expected_context_excluded_ids:
        raise RuntimeError(
            "context exclusions are not exactly the downstream turns after reviewed "
            f"contamination roots: {sorted(context_excluded_ids)}"
        )
    rows = [row for row in rows if str(row["case_id"]) in case_ids]
    if any(row.get("prompt_version") != SOURCE_PROMPT_VERSION for row in rows):
        raise RuntimeError(
            f"this audit only applies to source prompt {SOURCE_PROMPT_VERSION}"
        )

    override_sets = [
        set(PREMATURE_STOP_OVERRIDES),
        set(FORCED_STOP_OVERRIDES),
        set(CONTINUE_REWRITES),
        set(FULL_SEMANTIC_REWRITES),
    ]
    if any(
        left & right
        for index, left in enumerate(override_sets)
        for right in override_sets[index + 1 :]
    ):
        raise RuntimeError("semantic audit override sets overlap")
    override_ids = set().union(*override_sets)
    unknown = override_ids - raw_ids
    if unknown:
        raise RuntimeError(f"semantic audit contains unknown cases: {sorted(unknown)}")
    inactive_override_ids = override_ids - case_ids

    source_matrix = Counter(
        f"{row.get('expected_decision')}->{row.get('teacher_decision', {}).get('decision')}"
        for row in rows
    )
    expected_source_matrix = {
        "continue->continue": 1254,
        "continue->stop": 18,
        "stop->continue": 52,
        "stop->stop": 139,
    }
    if dict(source_matrix) != expected_source_matrix:
        raise RuntimeError(
            "source decision population changed; repeat semantic review before "
            f"applying this audit: {dict(source_matrix)}"
        )
    disagreement_ids = {
        str(row["case_id"])
        for row in rows
        if row.get("expected_decision")
        != row.get("teacher_decision", {}).get("decision")
    }
    decision_review_override_ids = (
        set(PREMATURE_STOP_OVERRIDES)
        | set(FORCED_STOP_OVERRIDES)
        | set(CONTINUE_REWRITES)
    ) & case_ids
    if len(disagreement_ids) != 70 or not decision_review_override_ids <= disagreement_ids:
        raise RuntimeError("semantic audit overrides no longer match the reviewed source")

    audited_rows: list[dict[str, Any]] = []
    actions: Counter[str] = Counter()
    source_grounding_issue_counts: Counter[str] = Counter()
    source_grounding_case_count = 0
    metadata_normalizations: Counter[str] = Counter()
    for row in rows:
        case_id = str(row["case_id"])
        case = case_by_id[case_id]
        if row.get("status") != "accepted" or row.get("quality_issues"):
            raise RuntimeError(f"source generation is not export-ready: {case_id}")
        original = TeacherDecision.from_mapping(row["teacher_decision"])
        decision = original
        audit: dict[str, Any] | None = None
        target_changed = False
        target_provenance = "deepseek_v1.5"
        original_grounding_issues = _grounding_issues(original, case)
        source_grounding_case_count += bool(original_grounding_issues)
        source_grounding_issue_counts.update(
            issue.split(":", 1)[0] for issue in original_grounding_issues
        )

        if case_id in PREMATURE_STOP_OVERRIDES:
            spec = PREMATURE_STOP_OVERRIDES[case_id]
            if original.decision != "stop":
                raise RuntimeError(f"expected premature STOP source: {case_id}")
            decision = replace(
                original,
                decision="continue",
                is_over=False,
                termination_reason="continue",
                goal_status="in_progress",
                communication_status="partial",
                response=str(spec["response"]),
                unresolved_goals=tuple(str(item) for item in spec["unresolved_goals"]),
                evidence=(),
            )
            audit = {"action": "restore_continue", "reason": spec["reason"]}
            target_changed = True
        elif case_id in FORCED_STOP_OVERRIDES:
            spec = FORCED_STOP_OVERRIDES[case_id]
            if original.decision != "continue":
                raise RuntimeError(f"expected delayed CONTINUE source: {case_id}")
            decision = _stop_decision(original, spec["termination_reason"])
            audit = {
                "action": "canonicalize_stop",
                "reason": spec["reason"],
                "termination_reason": spec["termination_reason"],
            }
            target_changed = True
        elif case_id in CONTINUE_REWRITES:
            spec = CONTINUE_REWRITES[case_id]
            if original.decision != "continue":
                raise RuntimeError(f"expected CONTINUE rewrite source: {case_id}")
            decision = replace(
                original,
                response=str(spec["response"]),
                unresolved_goals=tuple(str(item) for item in spec["unresolved_goals"]),
                goal_status="in_progress",
                communication_status="partial",
                evidence=(),
            )
            audit = {"action": "rewrite_continue", "reason": spec["reason"]}
            target_changed = True
        elif case_id in FULL_SEMANTIC_REWRITES:
            spec = FULL_SEMANTIC_REWRITES[case_id]
            if original.decision != "continue":
                raise RuntimeError(f"expected CONTINUE semantic rewrite source: {case_id}")
            decision = replace(
                original,
                response=str(spec["response"]),
                goal_status="in_progress",
                communication_status="partial",
                evidence=(),
            )
            audit = {"action": "repair_same_decision_semantics", "reason": spec["reason"]}
            target_changed = True
        elif original_grounding_issues:
            reference_issues = list(case.get("reference_grounding_issues", []))
            if reference_issues:
                raise RuntimeError(
                    "grounding repair requires an explicit semantic override because "
                    f"the historical reference is also invalid: {case_id} {reference_issues}"
                )
            grounded_reference = " ".join(
                str(case["reference_response"]).split()
            )
            decision = replace(
                original,
                response=grounded_reference,
                communication_status="partial",
                evidence=(),
            )
            audit = {
                "action": "repair_observable_grounding",
                "reason": "; ".join(original_grounding_issues),
                "repair_source": "reviewed_historical_reference",
            }
            target_changed = True
            target_provenance = "reviewed_historical_reference"
        elif case_id in disagreement_ids:
            audit = {
                "action": "retain_deepseek",
                "reason": (
                    "review confirmed that the Teacher corrects or more faithfully "
                    "advances the non-authoritative historical next-turn boundary"
                ),
            }

        if decision.decision == "continue" and decision.communication_status == "complete":
            decision = replace(decision, communication_status="partial")
            metadata_normalizations["continue_complete_to_partial"] += 1

        issues = _quality_issues(decision, case)
        if issues:
            raise RuntimeError(f"audited decision fails {issues}: {case_id}")
        if target_changed and target_provenance == "deepseek_v1.5":
            target_provenance = "human_semantic_audit"
        sft_record = build_sft_record(
            case,
            decision,
            prompt_version=str(row["prompt_version"]),
            quality_issues=[],
        )
        sft_record["metadata"]["target_provenance"] = target_provenance
        if audit is not None:
            sft_record["metadata"]["semantic_audit_version"] = AUDIT_VERSION
            sft_record["metadata"]["semantic_audit_action"] = audit["action"]

        value = dict(row)
        value["teacher_decision"] = decision.to_mapping()
        value["quality_issues"] = []
        value["sft_record"] = sft_record
        value["target_provenance"] = target_provenance
        if audit is not None:
            value["semantic_audit"] = {
                "version": AUDIT_VERSION,
                "scope": (
                    "decision disagreements plus full observable-grounding and "
                    "same-decision semantic review"
                ),
                "original_decision": original.decision,
                "original_response": original.response,
                **audit,
            }
            actions[str(audit["action"])] += 1
        audited_rows.append(value)

    _write_jsonl(args.output, audited_rows)
    summary = summarize_generations(audited_rows)
    if not summary["export_gate_passed"]:
        raise RuntimeError("audited batch failed the export gate")
    decision_disagreements = sum(
        row.get("expected_decision") != row["teacher_decision"]["decision"]
        for row in audited_rows
    )
    provenance = Counter(str(row["target_provenance"]) for row in audited_rows)
    report = {
        "audit_version": AUDIT_VERSION,
        "input": str(args.input.resolve()),
        "input_sha256": _sha256(args.input),
        "cases": str(args.cases.resolve()),
        "cases_sha256": _sha256(args.cases),
        "output": str(args.output.resolve()),
        "output_sha256": _sha256(args.output),
        "review_scope": {
            "historical_teacher_decision_disagreements_reviewed": len(
                disagreement_ids
            ),
            "raw_historical_teacher_decision_disagreements_reviewed": 70,
            "inactive_reviewed_overrides_after_context_cut": sorted(
                inactive_override_ids
            ),
            "source_decision_matrix": dict(source_matrix),
            "raw_rows": len(row_ids),
            "auditable_runtime_reachable_rows": len(rows),
            "context_excluded_rows": len(context_excluded_ids),
            "context_excluded_case_ids": sorted(context_excluded_ids),
            "same_decision_semantic_rewrites": len(FULL_SEMANTIC_REWRITES),
            "source_grounding_issue_counts": dict(source_grounding_issue_counts),
            "source_grounding_cases": source_grounding_case_count,
        },
        "semantic_actions": dict(actions),
        "metadata_normalizations": dict(metadata_normalizations),
        "target_provenance_counts": dict(provenance),
        "final_historical_teacher_decision_disagreements": decision_disagreements,
        "generation_summary": summary,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
