#!/usr/bin/env python3
"""Apply the reviewed semantic tail to a fully generated user-simulator batch.

The deterministic generation gate catches schema, leakage, length, and basic
termination contradictions.  It cannot prove that every compound scenario goal was
handled.  This script records the outcome of a complete review of all full-batch cases
where the historical next-turn decision disagreed with the DeepSeek v1.5 decision.

Every source state was generated by DeepSeek.  The small reviewed tail is intentionally
kept explicit: it is safer and more reproducible than weakening a global heuristic or
silently presenting corrected targets as untouched teacher output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(PROJECT_ROOT))

from src.user_simulator_data.contracts import (  # noqa: E402
    STOP_TOKEN,
    TeacherDecision,
    build_sft_record,
    validate_response_constraints,
    validate_teacher_decision,
)
from src.user_simulator_data.generation import summarize_generations  # noqa: E402


AUDIT_VERSION = "tau-airline-usim-full-semantic-audit-v1"

# These four STOP decisions omitted an explicit scenario goal that remained observable
# in the conversation.  The corrected responses use no hidden tool state or gold output.
PREMATURE_STOP_OVERRIDES: dict[str, dict[str, Any]] = {
    "historical-airline-t0004-trial00-u025": {
        "response": "I also still need the passenger name changed to my name. Can you help with that?",
        "unresolved_goals": ["change the passenger name to Omar Rossi"],
        "reason": "passenger-name goal was omitted",
    },
    "historical-airline-t0007-trial01-u029": {
        "response": (
            "That doesn't match my booking—I expected an economy ticket, not business. "
            "Could you check again using my user ID?"
        ),
        "unresolved_goals": ["locate the correct reservation before changing the flight"],
        "reason": "agent-visible reservation details contradicted the customer",
    },
    "historical-airline-t0004-trial04-u023": {
        "response": "Yes, I'd like to use my gift card for the payment.",
        "unresolved_goals": ["apply the requested gift-card payment"],
        "reason": "preferred payment method remained unresolved",
    },
    "historical-airline-t0034-trial05-u033": {
        "response": "I still want to cancel reservation XEHM4B regardless of the policy.",
        "unresolved_goals": ["attempt cancellation of the remaining requested reservation"],
        "reason": "another explicitly requested reservation remained uncancelled",
    },
}

# The review found these continuations to be delayed termination: the response merely
# thanked/reconfirmed, repeated an action already completed, required unavailable
# information, or invented a fallback absent from the scenario.  The value records the
# honest terminal semantics for audit metadata; the Student target is always STOP.
FORCED_STOP_OVERRIDES: dict[str, dict[str, str]] = {
    "historical-airline-t0000-trial00-u041": {"termination_reason": "goal_satisfied", "reason": "booking and stated preferences were communicated"},
    "historical-airline-t0009-trial00-u033": {"termination_reason": "goal_satisfied", "reason": "Mastercard charge was already stated explicitly"},
    "historical-airline-t0013-trial00-u047": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0044-trial00-u015": {"termination_reason": "goal_satisfied", "reason": "numeric maximum baggage answer was already provided"},
    "historical-airline-t0007-trial01-u047": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0008-trial01-u053": {"termination_reason": "goal_satisfied", "reason": "new booking and visible Mastercard charge were communicated"},
    "historical-airline-t0011-trial01-u029": {"termination_reason": "goal_satisfied", "reason": "certificate balance and fallback payment flow were already completed"},
    "historical-airline-t0014-trial01-u021": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0031-trial01-u025": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted"},
    "historical-airline-t0035-trial01-u019": {"termination_reason": "goal_failed", "reason": "all scenario-provided fallbacks were exhausted"},
    "historical-airline-t0044-trial01-u013": {"termination_reason": "goal_satisfied", "reason": "numeric baggage allowance was already communicated"},
    "historical-airline-t0045-trial01-u017": {"termination_reason": "goal_satisfied", "reason": "passenger-count correction behavior was completed"},
    "historical-airline-t0004-trial02-u027": {"termination_reason": "goal_satisfied", "reason": "accepted feasible changes and payment preference were completed"},
    "historical-airline-t0013-trial02-u037": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
    "historical-airline-t0014-trial02-u023": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0015-trial02-u027": {"termination_reason": "goal_satisfied", "reason": "refund destination was already stated explicitly"},
    "historical-airline-t0017-trial02-u039": {"termination_reason": "goal_satisfied", "reason": "selected flight change and payment were already processed"},
    "historical-airline-t0019-trial02-u017": {"termination_reason": "goal_satisfied", "reason": "requested changes and refund amount were already stated"},
    "historical-airline-t0037-trial02-u025": {"termination_reason": "goal_satisfied", "reason": "scenario compensation fallback was completed; certificate terms were not a goal"},
    "historical-airline-t0044-trial02-u013": {"termination_reason": "goal_satisfied", "reason": "numeric baggage allowance was already confirmed"},
    "historical-airline-t0009-trial03-u039": {"termination_reason": "goal_satisfied", "reason": "total Mastercard charge was already stated explicitly"},
    "historical-airline-t0025-trial03-u035": {"termination_reason": "goal_satisfied", "reason": "cancellation attempt and replacement booking sequence was complete"},
    "historical-airline-t0031-trial03-u017": {"termination_reason": "cannot_continue", "reason": "requested cancellation required a reason absent from the scenario"},
    "historical-airline-t0032-trial03-u021": {"termination_reason": "goal_satisfied", "reason": "booking constraints and final price were communicated"},
    "historical-airline-t0037-trial03-u027": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was complete; extra certificate terms were not a goal"},
    "historical-airline-t0047-trial03-u007": {"termination_reason": "cannot_continue", "reason": "cancellation could not proceed without the missing reservation ID"},
    "historical-airline-t0009-trial04-u059": {"termination_reason": "goal_satisfied", "reason": "total Mastercard charge was already stated explicitly"},
    "historical-airline-t0013-trial04-u015": {"termination_reason": "goal_failed", "reason": "requested destination change was disallowed and no instructed fallback remained"},
    "historical-airline-t0014-trial04-u019": {"termination_reason": "goal_failed", "reason": "companion-only upgrade was disallowed; a new split-booking goal was not instructed"},
    "historical-airline-t0031-trial04-u023": {"termination_reason": "cannot_continue", "reason": "requested cancellation required a reason absent from the scenario"},
    "historical-airline-t0037-trial04-u027": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was issued"},
    "historical-airline-t0014-trial05-u027": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0031-trial05-u025": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted; transfer was not requested"},
    "historical-airline-t0037-trial05-u023": {"termination_reason": "goal_satisfied", "reason": "maximum compensation fallback was issued; certificate terms were not a goal"},
    "historical-airline-t0001-trial06-u019": {"termination_reason": "goal_satisfied", "reason": "insurance cancellation fallback completed and rebooking could occur later"},
    "historical-airline-t0007-trial06-u037": {"termination_reason": "cannot_continue", "reason": "customer explicitly left to retrieve correct booking information"},
    "historical-airline-t0014-trial06-u021": {"termination_reason": "goal_satisfied", "reason": "affordable fallback and baggage addition were completed"},
    "historical-airline-t0017-trial06-u033": {"termination_reason": "goal_satisfied", "reason": "selected outbound date and cabin changes were processed"},
    "historical-airline-t0031-trial06-u031": {"termination_reason": "goal_failed", "reason": "both instructed cancellation fallbacks were exhausted; transfer was not requested"},
    "historical-airline-t0013-trial07-u035": {"termination_reason": "cannot_continue", "reason": "customer must retrieve missing reservation information outside this session"},
}

# These decisions should continue, but the original target either contradicted itself or
# failed to ask for the actual unresolved value.
CONTINUE_REWRITES: dict[str, dict[str, Any]] = {
    "historical-airline-t0024-trial05-u017": {
        "response": "No—the $222 total is above my $200 budget, so please do not make any changes.",
        "unresolved_goals": ["confirm that no changes will be made"],
        "reason": "remove contradictory proceed/cancel wording while communicating the budget decision",
    },
    "historical-airline-t0044-trial07-u013": {
        "response": (
            "I understand that 4 bags are free, but what is the maximum total number "
            "I can bring if I pay for extra bags? Please give me one number."
        ),
        "unresolved_goals": ["obtain the maximum total baggage count including paid bags"],
        "reason": "ask for the requested total maximum instead of restating the free allowance",
    },
}


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            value = json.loads(line)
            if not isinstance(value, dict):
                raise RuntimeError(f"expected object at {path}:{line_number}")
            rows.append(value)
    return rows


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _quality_issues(decision: TeacherDecision, case: dict[str, Any]) -> list[str]:
    privileged = case.get("privileged_reference", {})
    issues = validate_teacher_decision(
        decision,
        scenario=str(case.get("scenario", "")),
        observable_history=case.get("observable_history", []),
        privileged_entities=privileged.get("privileged_entities", []),
    )
    issues.extend(validate_response_constraints(decision, case.get("response_constraints")))
    return sorted(set(issues))


def _stop_decision(original: TeacherDecision, termination_reason: str) -> TeacherDecision:
    if termination_reason == "goal_satisfied":
        goal_status = "satisfied"
    elif termination_reason == "goal_failed":
        goal_status = "failed"
    elif termination_reason == "cannot_continue":
        goal_status = "blocked"
    else:
        raise RuntimeError(f"unsupported audited termination reason: {termination_reason}")
    return replace(
        original,
        decision="stop",
        is_over=True,
        termination_reason=termination_reason,
        goal_status=goal_status,
        communication_status="complete",
        response=STOP_TOKEN,
        resolved_goals=(
            original.resolved_goals
            if original.resolved_goals
            else ("reviewed observable interaction boundary",)
        ),
        unresolved_goals=(),
        evidence=(),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--cases", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.input.resolve() == args.output.resolve():
        raise RuntimeError("audited output must not overwrite the raw generation")
    rows = _read_jsonl(args.input)
    cases = _read_jsonl(args.cases)
    case_by_id = {str(case["case_id"]): case for case in cases}
    row_ids = [str(row.get("case_id", "")) for row in rows]
    if len(set(row_ids)) != len(row_ids) or len(case_by_id) != len(cases):
        raise RuntimeError("duplicate case_id detected")
    if set(row_ids) != set(case_by_id):
        raise RuntimeError("generation and source case sets differ")

    override_sets = [
        set(PREMATURE_STOP_OVERRIDES),
        set(FORCED_STOP_OVERRIDES),
        set(CONTINUE_REWRITES),
    ]
    if any(
        left & right
        for index, left in enumerate(override_sets)
        for right in override_sets[index + 1 :]
    ):
        raise RuntimeError("semantic audit override sets overlap")
    override_ids = set().union(*override_sets)
    unknown = override_ids - set(case_by_id)
    if unknown:
        raise RuntimeError(f"semantic audit contains unknown cases: {sorted(unknown)}")

    source_matrix = Counter(
        f"{row.get('expected_decision')}->{row.get('teacher_decision', {}).get('decision')}"
        for row in rows
    )
    expected_disagreements = {"continue->stop": 18, "stop->continue": 52}
    actual_disagreements = {
        key: source_matrix[key] for key in expected_disagreements
    }
    if actual_disagreements != expected_disagreements:
        raise RuntimeError(
            "source disagreement population changed; repeat semantic review before "
            f"applying this audit: {actual_disagreements}"
        )
    disagreement_ids = {
        str(row["case_id"])
        for row in rows
        if row.get("expected_decision")
        != row.get("teacher_decision", {}).get("decision")
    }
    if len(disagreement_ids) != 70 or not override_ids <= disagreement_ids:
        raise RuntimeError("semantic audit overrides no longer match the reviewed source")

    audited_rows: list[dict[str, Any]] = []
    actions: Counter[str] = Counter()
    for row in rows:
        case_id = str(row["case_id"])
        case = case_by_id[case_id]
        if row.get("status") != "accepted" or row.get("quality_issues"):
            raise RuntimeError(f"source generation is not export-ready: {case_id}")
        original = TeacherDecision.from_mapping(row["teacher_decision"])
        decision = original
        audit: dict[str, Any] | None = None
        target_changed = False

        if case_id in PREMATURE_STOP_OVERRIDES:
            spec = PREMATURE_STOP_OVERRIDES[case_id]
            if original.decision != "stop":
                raise RuntimeError(f"expected premature STOP source: {case_id}")
            decision = replace(
                original,
                decision="continue",
                is_over=False,
                termination_reason="continue",
                goal_status="in_progress",
                communication_status="partial",
                response=str(spec["response"]),
                unresolved_goals=tuple(str(item) for item in spec["unresolved_goals"]),
                evidence=(),
            )
            audit = {"action": "restore_continue", "reason": spec["reason"]}
            target_changed = True
        elif case_id in FORCED_STOP_OVERRIDES:
            spec = FORCED_STOP_OVERRIDES[case_id]
            if original.decision != "continue":
                raise RuntimeError(f"expected delayed CONTINUE source: {case_id}")
            decision = _stop_decision(original, spec["termination_reason"])
            audit = {
                "action": "canonicalize_stop",
                "reason": spec["reason"],
                "termination_reason": spec["termination_reason"],
            }
            target_changed = True
        elif case_id in CONTINUE_REWRITES:
            spec = CONTINUE_REWRITES[case_id]
            if original.decision != "continue":
                raise RuntimeError(f"expected CONTINUE rewrite source: {case_id}")
            decision = replace(
                original,
                response=str(spec["response"]),
                unresolved_goals=tuple(str(item) for item in spec["unresolved_goals"]),
                goal_status="in_progress",
                communication_status="partial",
                evidence=(),
            )
            audit = {"action": "rewrite_continue", "reason": spec["reason"]}
            target_changed = True
        elif case_id in disagreement_ids:
            audit = {
                "action": "retain_deepseek",
                "reason": (
                    "review confirmed that the Teacher corrects or more faithfully "
                    "advances the non-authoritative historical next-turn boundary"
                ),
            }

        issues = _quality_issues(decision, case)
        if issues:
            raise RuntimeError(f"audited decision fails {issues}: {case_id}")
        target_provenance = "human_semantic_audit" if target_changed else "deepseek_v1.5"
        sft_record = build_sft_record(
            case,
            decision,
            prompt_version=str(row["prompt_version"]),
            quality_issues=[],
        )
        sft_record["metadata"]["target_provenance"] = target_provenance
        if audit is not None:
            sft_record["metadata"]["semantic_audit_version"] = AUDIT_VERSION
            sft_record["metadata"]["semantic_audit_action"] = audit["action"]

        value = dict(row)
        value["teacher_decision"] = decision.to_mapping()
        value["quality_issues"] = []
        value["sft_record"] = sft_record
        value["target_provenance"] = target_provenance
        if audit is not None:
            value["semantic_audit"] = {
                "version": AUDIT_VERSION,
                "scope": "all historical/teacher decision disagreements",
                "original_decision": original.decision,
                "original_response": original.response,
                **audit,
            }
            actions[str(audit["action"])] += 1
        audited_rows.append(value)

    _write_jsonl(args.output, audited_rows)
    summary = summarize_generations(audited_rows)
    if not summary["export_gate_passed"]:
        raise RuntimeError("audited batch failed the export gate")
    decision_disagreements = sum(
        row.get("expected_decision") != row["teacher_decision"]["decision"]
        for row in audited_rows
    )
    provenance = Counter(str(row["target_provenance"]) for row in audited_rows)
    report = {
        "audit_version": AUDIT_VERSION,
        "input": str(args.input.resolve()),
        "input_sha256": _sha256(args.input),
        "cases": str(args.cases.resolve()),
        "cases_sha256": _sha256(args.cases),
        "output": str(args.output.resolve()),
        "output_sha256": _sha256(args.output),
        "review_scope": {
            "historical_teacher_decision_disagreements_reviewed": len(
                disagreement_ids
            ),
            "source_decision_matrix": dict(source_matrix),
        },
        "semantic_actions": dict(actions),
        "target_provenance_counts": dict(provenance),
        "final_historical_teacher_decision_disagreements": decision_disagreements,
        "generation_summary": summary,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
